name: janus_streaming_app
description: A simple Janus streaming Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_webrtc: 0.9.12
  http: ^0.13.6
  intl: ^0.18.0
  mqtt_client: ^9.8.1
  web_socket_channel: ^2.4.0  # 추가
  typed_data: ^1.3.2  # 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true