name: janus_streaming_app
description: A simple Janus streaming Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_webrtc: 0.9.12
  http: ^0.13.6
  intl: ^0.18.0
  mqtt_client: ^9.8.1
  web_socket_channel: ^2.4.0  # 추가
  typed_data: ^1.3.2  # 추가
  # 상태 관리
  provider: ^6.1.1
  # UI
  cupertino_icons: ^1.0.6

  # alert
  flutter_local_notifications: ^17.2.3
  # GitHub에서 직접 가져오기 (Flutter 3.29+ 호환)
  workmanager:
      git:
        url: https://github.com/fluttercommunity/flutter_workmanager.git
        ref: main
        path: workmanager
  permission_handler: ^11.1.0
  flutter_background_service: ^5.0.5  # 지속적인 서비스용
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/car.png"  # ✅ 아이콘 경로
  adaptive_icon_background: "#ffffff"     # (선택) Android 8.0 이상 배경
  adaptive_icon_foreground: "assets/icon/car.png"  # (선택)
